### ISSUE TITLE
Adding Wouter Knoben's contribution to the ERA5 downloads

### ISSUE THREAD

**Issue by kasra-keshavarz** [kasra-keshavarz/datatool#6]
# Issue description

The download scripts available at [here](https://github.com/kasra-keshavarz/datatool/tree/master/era5#downloading-original-era5-data) need to acknowledge Wouter Knoben's contributions including parts of the [CWARHM workflow](https://github.com/CH-Earth/CWARHM).

**Comment by ShervanGharari** [comment]
It is cleaner to point at the CWARHM [repo](https://github.com/CH-Earth/CWARHM/tree/main/3a_forcing/1a_download_forcing) instead of having the [zip](https://github.com/kasra-keshavarz/datatool/blob/master/era5/ERA5_downloads.zip) file.
Also mentioned Guoqiang as the data on Graham was downloaded by him to my knowledge.
In general sense, the datatool, should be separate from the download script and credit. Users may want to use it in different place with different download tools, or the version of ERA5 they have. Something to consider on where the best place of credit should be.

**Comment by kasra-keshavarz** [comment]
Solved with #9
